# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#


##
# Book Insert
# Book.create(:title =>"", :description =>  "", :price => 74.00, :author => "", :isbn => "", :category => "")
Book.create(:title => "Release It!: Design and Deploy Production-Ready Software", :description => "Whether it's in Java, .NET, or Ruby on Rails, getting your application ready to ship is only half the battle. Did you design your system to survivef a sudden rush of visitors from Digg or Slashdot? Or an influx of real world customers from 100 different countries? Are you ready for a world filled with flakey networks, tangled databases, and impatient users?", :price => 37.72, :author => "Michael T. Nygard", :isbn => "0978739213", :category => "science")

Book.create(:title =>"Design Patterns: Elements of Reusable Object-Oriented Software", :description =>  "This book isn't an introduction to object-oriented technology or design. Many books already do a good job of that. This book assumes you are reasonably proficient in at least one object-oriented programming language, and you should have some experience in object-oriented design as well. You definitely shouldn't have to rush to the nearest dictionary the moment we mention types and polymorphism, or interface as opposed to implementation inheritance.On the other hand, this isn't an advanced ", :price => 74.00, :author => "Erich Gamma", :isbn => "0201633612", :category => "engineering")

Book.create(:title =>"Linchpin: Are You Indispensable?", :description =>  "The only way to get what you're worth is to stand out, to exert emotional labor, to be seen as indispensable, and to produce interactions that organizations and people care deeply about.", :price => 17.39, :author => "Seth Godin", :isbn => "1591844096", :category => "self-growth")

Book.create(:title =>"How to Win Friends and Influence People", :description =>  "This grandfather of all people-skills books was first published in 1937. It was an overnight hit, eventually selling 15 million copies. How to Win Friends and Influence People is just as useful today as it was when it was first published, because Dale Carnegie had an understanding of human nature that will never be outdated. Financial success, Carnegie believed, is due 15 percent to professional knowledge and 85 percent to \"the ability to express ideas, to assume leadership, and to arouse enthusiasm among people.\" He teaches these skills through underlying principles of dealing with people so that they feel important and appreciated. He also emphasizes fundamental techniques for handling people without making them feel manipulated. Carnegie says you can make someone want to do what you want them to by seeing the situation from the other person's point of view and \"arousing in the other person an eager want.\" You learn how to make people like you, win people over to your way of thinking, and change people without causing offense or arousing resentment. For instance, \"let the other person feel that the idea is his or hers,\" and \"talk about your own mistakes before criticizing the other person.\" Carnegie illustrates his points with anecdotes of historical figures, leaders of the business world, and everyday folks. --Joan Price --This text refers to the Mass Market Paperback edition.", :price => 14.00, :author => "Dale Carnegie", :isbn => "0671027034", :category => "self-growth")

Book.create(:title =>"why's (poignant) guide to Ruby", :description =>  "This is just a small Ruby book. It won’t crush you. It’s light as a feather (because I haven’t finished it yet—hehe). And there’s a reason this book will stay light: because Ruby is simple to learn.

[Why’s (Poignant) Guide to Ruby is released under the Attribution-ShareAlike License. So, yes, please distribute it and print it and read it leisurely in your housecoat.]", :price => 40.00, :author => "why the lucky stiff", :isbn => "1511878037", :category => "engineering")

Book.create(:title =>"JavaScript: The Good Parts", :description =>  "Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript that's more reliable, readable, and maintainable than the language as a whole—a subset you can use to create truly extensible and efficient code.", :price => 25.00, :author => "Douglas Crockford", :isbn => "0596517742", :category => "engineering")

Book.create(:title =>"The Circle", :description =>  "When Mae Holland is hired to work for the Circle, the world’s most powerful internet company, she feels she’s been given the opportunity of a lifetime. The Circle, run out of a sprawling California campus, links users’ personal emails, social media, banking, and purchasing with their universal operating system, resulting in one online identity and a new age of civility and transparency. As Mae tours the open-plan office spaces, the towering glass dining facilities, the cozy dorms for those who spend nights at work, she is thrilled with the company’s modernity and activity. There are parties that last through the night, there are famous musicians playing on the lawn, there are athletic activities and clubs and brunches, and even an aquarium of rare fish retrieved from the Marianas Trench by the CEO. Mae can’t believe her luck, her great fortune to work for the most influential company in the world—even as life beyond the campus grows distant, even as a strange encounter with a colleague leaves her shaken, even as her role at the Circle becomes increasingly public. What begins as the captivating story of one woman’s ambition and idealism soon becomes a heart-racing novel of suspense, raising questions about memory, history, privacy, democracy, and the limits of human knowledge.", :price => 13.00, :author => "Dave Eggers", :isbn => "B00EGMHKBA", :category => "fiction")

